name: 📦Auto Build for N
run-name: 📦 ${{ github.actor }} @ Github Action

on:
  push:
    branches: [ "n" ]
  pull_request:
    branches: [ "n" ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⏰ Set Timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      - name: 👨🏻‍💻 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}
      - name: ☕ Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle
      - name: 🤝 Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          gradle-version: wrapper

      - name: ☎️ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🔥 Build with Gradle
        run: ./gradlew assembleRelease -Pversion=${{ github.ref_name }}

      - name: 📊 Locate APKs and Set Outputs
        id: locate_apks
        run: |
          release_dir="app/build/outputs/apk/release"
          arm64_apk=$(find "$release_dir" -name "*-arm64-v8a-*.apk" | head -n 1)
          armv7_apk=$(find "$release_dir" -name "*-armeabi-v7a-*.apk" | head -n 1)
          x86_apk=$(find "$release_dir" -name "*-x86-*.apk" | head -n 1)
          x86_64_apk=$(find "$release_dir" -name "*-x86_64-*.apk" | head -n 1)
          universal_apk=$(find "$release_dir" -name "*-universal-*.apk" | head -n 1)
          echo "arm64_apk=$arm64_apk" >> $GITHUB_OUTPUT
          echo "armv7_apk=$armv7_apk" >> $GITHUB_OUTPUT
          echo "x86_apk=$x86_apk" >> $GITHUB_OUTPUT
          echo "x86_64_apk=$x86_64_apk" >> $GITHUB_OUTPUT
          echo "universal_apk=$universal_apk" >> $GITHUB_OUTPUT

      - name: 🚀 Upload APK - arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          name: apk-arm64-v8a
          path: ${{ steps.locate_apks.outputs.arm64_apk }}

      - name: 🚀 Upload APK - armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          name: apk-armeabi-v7a
          path: ${{ steps.locate_apks.outputs.armv7_apk }}

      - name: 🚀 Upload APK - x86
        uses: actions/upload-artifact@v4
        with:
          name: apk-x86
          path: ${{ steps.locate_apks.outputs.x86_apk }}

      - name: 🚀 Upload APK - x86_64
        uses: actions/upload-artifact@v4
        with:
          name: apk-x86_64
          path: ${{ steps.locate_apks.outputs.x86_64_apk }}

      - name: 🚀 Upload APK - universal
        uses: actions/upload-artifact@v4
        with:
          name: apk-universal
          path: ${{ steps.locate_apks.outputs.universal_apk }}
